name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'sq-simulator.GTX'
      - 'examples/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create release
        id: release
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Rename assets according to the version
        env:
          VERSION: ${{ steps.release.outputs.resolved_version }}
        run: |
          set -u
          mv examples/example-f.gxw "examples/example-f_v${VERSION}.gxw"
          mv examples/example-q.gxw "examples/example-q_v${VERSION}.gxw"
          mv examples/example-iqf.gx3 "examples/example-iqf_v${VERSION}.gx3"
          mv examples/example-iqr.gx3 "examples/example-iqr_v${VERSION}.gx3"
          mv sq-simulator.GTX "sq-simulator_v${VERSION}.GTX"
      - name: Upload assets to the release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ steps.release.outputs.tag_name }}
        run: |
          gh release upload "$TAG" sq-simulator*.GTX examples/* --clobber
